### ISSUE TITLE
Trouble using API with docker-compose version

### ISSUE THREAD

**Issue by sjb351** [eclipse-aaspe/server#322]
Thank you for all the great work!

I successfully set up a server on AWS (and locally) with an aasx file. The user interface seems to work well but I can't get all the API's to work. APIs like GET /submodels return:
```
{
  "errors": {
    "level": [
      "The level field is required."
    ],
    "extent": [
      "The extent field is required."
    ]
  },
  "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-bf7c0aa3d6c1cd7179b0e3bb83c4c304-fbed7fa5290d1d33-00"
}
```

The docker compose file is below and the server URL is http://ec2-13-42-56-55.eu-west-2.compute.amazonaws.com/ 

```
services:
  aasx-server:
    container_name: aasx-server
    image: docker.io/adminshellio/aasx-server-blazor-for-demo:main
    ports:
      - 80:5001
    environment:
      - Kestrel__Endpoints__Http__Url=http://*:5001
    volumes:
      - ./aasxs:/AasxServerBlazor/aasxs
    command: --no-security --external-blazor
```

Can you suggest anything to change? I think it might be a mistake in way I am using the API or the docker set up
