### ISSUE TITLE
[Bug]: Invoking /shells?idShort=ExampleMotor returns error 500

### ISSUE THREAD

**Issue by otto-ifak** [eclipse-aaspe/server#331]
### Describe the bug

Invoking `GET /shells?idShort=ExampleMotor` returns status code 500 with the following error message:

```json
{
  "Messages": [
    {
      "Code": "InternalServerError",
      "CorrelationId": null,
      "MessageType": "Error",
      "Text": "Object reference not set to an instance of an object.",
      "Timestamp": "07/17/2024 17:33:55"
    }
  ]
}
```

### To reproduce

I am using the following docker-compose.yml to reproduce:

```yml
services:
  aasx-server:
    container_name: aasx-server
    image: docker.io/adminshellio/aasx-server-blazor-for-demo:main
    restart: unless-stopped
    ports:
      - 5001:5001
    environment:
      - Kestrel__Endpoints__Http__Url=http://*:5001
    volumes:
      - ./aasxs:/usr/share/aasxs
    command: --no-security --data-path /usr/share/aasxs --external-blazor localhost
```

### Expected Behaviour

Should return a list containing one entry, namely the AAS with idShort ExampleMotor
