### ISSUE TITLE
[Bug]: GET /shells/$reference returns 500

### ISSUE THREAD

**Issue by otto-ifak** [eclipse-aaspe/server#334]
### Describe the bug

Invoking `GET /shells/$reference` returns error code 500.

### To reproduce

I am using the following `docker-compose.yml`:

```yml
services:
  aasx-server:
    container_name: aasx-server
    image: docker.io/adminshellio/aasx-server-blazor-for-demo@sha256:f2010238503edc6c77ce37cd60f8b640431c768c6dd2a924f9c29f24c7e590dc # main
    restart: unless-stopped
    ports:
      - 5001:5001
    environment:
      - Kestrel__Endpoints__Http__Url=http://*:5001
    volumes:
      - ./aasxs:/usr/share/aasxs
    command: --no-security --data-path /usr/share/aasxs --external-blazor localhost
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```
