### ISSUE TITLE
[Bug]:  GET /shells/{aasIdentifier}/submodels not implemented

### ISSUE THREAD

**Issue by otto-ifak** [eclipse-aaspe/server#335]
### Describe the bug

Invoking `GET /shells/aHR0cDovL2N1c3RvbWVyLmNvbS9hYXMvOTE3NV83MDEzXzcwOTFfOTE2OA==` returns

```json
{
  "idShort": "ExampleMotor",
  "id": "http://customer.com/aas/9175_7013_7091_9168",
  "assetInformation": {
    "assetKind": "Instance",
    "globalAssetId": "http://customer.com/assets/KHBVZJSQKIY",
    "defaultThumbnail": {
      "path": "/MotorI40.JPG"
    }
  },
  "submodels": [
    {
      "type": "ModelReference",
      "keys": [
        {
          "type": "Submodel",
          "value": "http://i40.customer.com/type/1/1/F13E8576F6488342"
        }
      ]
    },
    {
      "type": "ModelReference",
      "keys": [
        {
          "type": "Submodel",
          "value": "http.//i40.customer.com/type/1/1/7A7104BDAB57E184"
        }
      ]
    },
    {
      "type": "ModelReference",
      "keys": [
        {
          "type": "Submodel",
          "value": "http://i40.customer.com/instance/1/1/AC69B1CB44F07935"
        }
      ]
    },
    {
      "type": "ModelReference",
      "keys": [
        {
          "type": "Submodel",
          "value": "http://i40.customer.com/type/1/1/1A7B62B529F19152"
        }
      ]
    }
  ],
  "modelType": "AssetAdministrationShell"
}
```

But chaining it to invoke `GET /shells/aHR0cDovL2N1c3RvbWVyLmNvbS9hYXMvOTE3NV83MDEzXzcwOTFfOTE2OA==/submodels` does not work.

### To reproduce

I am using the following `docker-compose.yml`:

```yml
services:
  aasx-server:
    container_name: aasx-server
    image: docker.io/adminshellio/aasx-server-blazor-for-demo@sha256:f2010238503edc6c77ce37cd60f8b640431c768c6dd2a924f9c29f24c7e590dc # main
    restart: unless-stopped
    ports:
      - 5001:5001
    environment:
      - Kestrel__Endpoints__Http__Url=http://*:5001
    volumes:
      - ./aasxs:/usr/share/aasxs
    command: --no-security --data-path /usr/share/aasxs --external-blazor localhost
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```
